In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("D:/downloads/email_data.csv")

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize
from nltk.stem import WordNetLemmatizer
lemmatizer= WordNetLemmatizer()

In [6]:
corpus=[]
for i in range(len(df['Message'])):
    review= re.sub('[^a-zA-Z]',' ', df['Message'][i])
    review= review.lower()
    review= review.split()
    review= [lemmatizer.lemmatize(word) for word in review]
    review= ' '.join(review)
    corpus.append(review)


In [7]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, df['Message']) if i<1]


[[0, '', '645'], [0, '', ':)'], [0, '', ':-) :-)']]

In [8]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [9]:
from gensim.utils import simple_preprocess

In [10]:
words=[]
for sen in corpus:
    sen_tokens = sent_tokenize(sen)
    for s in sen_tokens:
        words.append(simple_preprocess(s))

In [11]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [12]:
import gensim
from gensim.models import Word2Vec


In [13]:
model= Word2Vec(words)

In [14]:
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'she',
 'home',
 'stop',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'phone',
 'hi',
 'week',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope

In [15]:
model.corpus_count

5569

In [16]:
model.wv.similar_by_word('good')

[('my', 0.998432993888855),
 ('day', 0.9982751607894897),
 ('where', 0.9982514381408691),
 ('wa', 0.9982376098632812),
 ('morning', 0.9981362223625183),
 ('not', 0.9980737566947937),
 ('all', 0.998049795627594),
 ('very', 0.9980374574661255),
 ('about', 0.997948408126831),
 ('night', 0.9979387521743774)]

In [17]:
model.wv['good']

array([-0.26374775,  0.41574582,  0.0176243 ,  0.2427345 ,  0.03687001,
       -0.6786399 ,  0.22345266,  0.78767717, -0.32765788, -0.11629598,
       -0.18279542, -0.64239883, -0.03936142,  0.16045155,  0.22056288,
       -0.3413971 ,  0.13964461, -0.3714389 , -0.07371221, -0.77269346,
        0.24615654,  0.27908722,  0.11012413, -0.27904394, -0.1339003 ,
       -0.00936166, -0.48848757, -0.348754  , -0.32006902,  0.03935664,
        0.4323705 , -0.08089704,  0.15247376, -0.32437807, -0.195729  ,
        0.5731464 ,  0.05781868, -0.21332945, -0.09336776, -0.5878934 ,
        0.1127892 , -0.29244488, -0.24623935,  0.03897868,  0.34775198,
       -0.01470773, -0.3965301 , -0.16737297,  0.09626176,  0.16614011,
        0.33810604, -0.25976443, -0.2177527 ,  0.05447974, -0.08314768,
        0.25081378,  0.28094763,  0.12253249, -0.36176124,  0.16099624,
       -0.10737338,  0.15188396, -0.09242434, -0.21789335, -0.4032442 ,
        0.31510496,  0.15594375,  0.27437347, -0.49737495,  0.51

In [18]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [19]:

VECTOR_SIZE = model.vector_size  

def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv]

    if len(vectors) == 0:
        return np.zeros(VECTOR_SIZE)   

    return np.mean(vectors, axis=0)    


In [20]:
import numpy as np

In [21]:
from tqdm import tqdm
x=[]
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))

100%|██████████| 5569/5569 [00:00<00:00, 28491.96it/s]


In [22]:
x

[array([-0.17412437,  0.28416327,  0.03270211,  0.17950071,  0.03033109,
        -0.51213676,  0.15036148,  0.56489104, -0.21820779, -0.08895723,
        -0.14595288, -0.43752253, -0.07225711,  0.11898883,  0.17928343,
        -0.23438644,  0.09160859, -0.2866778 , -0.05520842, -0.5413876 ,
         0.1444471 ,  0.20030095,  0.06381797, -0.19667915, -0.08669032,
        -0.00368218, -0.3874753 , -0.24443999, -0.22182176,  0.04219039,
         0.30917802, -0.05699632,  0.0977812 , -0.22315617, -0.15095665,
         0.4136584 ,  0.05912109, -0.15925184, -0.0915793 , -0.40996447,
         0.08783647, -0.22533897, -0.19907261,  0.00955881,  0.25751445,
        -0.03008798, -0.27625498, -0.10653982,  0.08799929,  0.1237762 ,
         0.20178576, -0.19065715, -0.12616245,  0.06852905, -0.09374849,
         0.17856719,  0.18384698,  0.07275122, -0.2571975 ,  0.12625827,
        -0.058073  ,  0.10614381, -0.04363857, -0.1605499 , -0.27738893,
         0.24284697,  0.11584971,  0.19394913, -0.3

In [23]:
len(x)

5569

In [24]:
x[0].shape

(100,)

In [25]:
y= df[list(map(lambda x : len(x)>0, corpus))]
y=y.iloc[:,0]

In [26]:
y.shape

(5569,)

In [27]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y=encoder.fit_transform(y)
y

array([0, 0, 1, ..., 0, 0, 0], shape=(5569,))

In [28]:
x_new= pd.DataFrame()
for i in range(0,len(x)):
    row=pd.DataFrame(x[i].reshape(1,-1))
    x_new=pd.concat([x_new,row],ignore_index=True)

In [29]:
x_new.shape

(5569, 100)

In [30]:
x_new.head()

0         1         2         3         4         5         6   \
0 -0.174124  0.284163  0.032702  0.179501  0.030331 -0.512137  0.150361   
1 -0.157140  0.246433  0.025251  0.159777  0.028270 -0.453011  0.123426   
2 -0.151655  0.282838  0.055453  0.211158  0.029817 -0.576960  0.139897   
3 -0.245423  0.388941  0.037662  0.243038  0.043043 -0.679928  0.202107   
4 -0.218458  0.329823  0.036731  0.202144  0.047267 -0.591862  0.167360   

         7         8         9   ...        90        91        92        93  \
0  0.564891 -0.218208 -0.088957  ...  0.296130  0.135378  0.066289  0.082123   
1  0.491774 -0.186046 -0.065500  ...  0.262061  0.115369  0.055315  0.071352   
2  0.593679 -0.219327 -0.099475  ...  0.285695  0.137453  0.067174  0.088649   
3  0.754664 -0.303518 -0.114730  ...  0.405433  0.179742  0.082364  0.118217   
4  0.658540 -0.264390 -0.107083  ...  0.357762  0.148753  0.072053  0.100944   

         94        95        96        97        98        99  
0  0.393209  0.351028  0.106290 -0.191762  0.145191 -0.084919  
1  0.340280  0.298795  0.088325 -0.176363  0.118512 -0.071885  
2  0.397551  0.351068  0.102046 -0.202098  0.152912 -0.100225  
3  0.521210  0.473576  0.139212 -0.270170  0.188333 -0.101436  
4  0.449337  0.409974  0.117443 -0.242060  0.171303 -0.099478  

[5 rows x 100 columns]

In [31]:
x=x_new

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25)

In [33]:
x_train.shape,x_test.shape

((4176, 100), (1393, 100))

In [34]:
y_test.shape


(1393,)

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()

In [36]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [37]:
y_pred= rf.predict(x_test)

In [38]:
from sklearn.metrics import accuracy_score,f1_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))

0.9784637473079684


In [39]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1221
           1       0.92      0.90      0.91       172

    accuracy                           0.98      1393
   macro avg       0.95      0.95      0.95      1393
weighted avg       0.98      0.98      0.98      1393



In [40]:
print(confusion_matrix(y_test,y_pred))

[[1208   13]
 [  17  155]]


In [41]:
import pickle

with open("rf_model.pkl", "wb") as f:
    pickle.dump(rf, f)

with open("w2v_model.pkl", "wb") as f:
    pickle.dump(model, f)
